Stat svc
Sintsoft/java-explore-with-me pull request #5
Opened 2023-08-31 12:32 UTC by Sintsoft

4 дня я мучался с докером.

2023-09-01 07:36 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        Map<String, Object> parameters = Map.of(
https://www.concretepage.com/java/java-9/java-map-of-and-map-ofentries

Таким образом ты строишь неизменяемый `Map`.
А потом пытаешься добавить в него значения, через `.put()` это не сработает, и будет ошибка если список не пустой

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        }
Не очень понятно, что ты с помощью этого хочешь сделать, если положить по ключу список, то можно сразу это сделать без перебора значений

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-server/src/main/java/ru/practicum/repository/StatStorage.java
> +    public List<StatUriHitsResponseDTO> getStats(LocalDateTime start,
Это тоже имеет смысл пометить, как `Transactional`, только  с параметром `readonly = true`

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-server/src/main/java/ru/practicum/repository/StatStorage.java
> +        return jdbc.queryForStream(sql.toString(), new StatisticMapper()).collect(Collectors.toList());
Методы `jdbcTemplate` позволяют использовать именованные или порядковые параметры, с ними этот метод получился бы куда проще

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-server/src/main/java/ru/practicum/repository/StatStorage.java
> +                    rs.getInt(3));
По возможности лучше использовать `columnLabel`, поскольку он меняется куда реже, чем порядок колонок в запросе

2023-09-01 07:36 UTC, LexLippi commented on ewm-statistic/statistic-server/src/main/resources/schema.sql
> +	uri text not null,
Ограничения сверху в 2000-3000 символов вполне достаточно

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

2023-09-01 12:50 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        Map<String, Object> parameters = Map.of(
fixed

2023-09-01 12:51 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        }
fixed

2023-09-01 12:51 UTC, Sintsoft commented on ewm-statistic/statistic-server/src/main/java/ru/practicum/repository/StatStorage.java
> +        return jdbc.queryForStream(sql.toString(), new StatisticMapper()).collect(Collectors.toList());
fixed

2023-09-01 12:51 UTC, Sintsoft commented on ewm-statistic/statistic-server/src/main/resources/schema.sql
> +	uri text not null,
fixed

2023-09-02 07:20 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих этапах диплома!

2023-09-02 17:05 UTC, merged