Main svc
Sintsoft/java-explore-with-me pull request #6
Opened 2023-09-13 20:35 UTC by Sintsoft

Тестировал через постман

2023-09-17 08:09 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-09-17 08:09 UTC, LexLippi commented on ewm-statistic/statistic-client/pom.xml
> +        </dependency>
Реально в каждом `pom`-файле нужно?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/resources/schema.sql
> +    status VARCHAR(32),
может быть `null`?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/resources/schema.sql
> +    category_id BIGINT REFERENCES categories (id),
Точно все эти поля могут быть `null`?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/resources/schema.sql
> +    event_id BIGINT REFERENCES events (id),
могут быть `null`?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/paticipation/enums/ParticipationRequestStatus.java
> +    private String code;
Обычно используются теги, если они отличаются от названий, иначе нет смысла

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/paticipation/dto/ParticipationDecisionResponseDTO.java
> +    List<ParicipationResponseDTO> rejectedRequests;
модификаторы доступа?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/paticipation/dto/EventPartisipationDecisionDTO.java
> +    String status;
модификаторы

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            // TODO available
если сделано, то убрать
если нет, то наверное надо сделать?

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            }
Аналогично можно сделать:

```java
list.stream().toArray(String[] ::new);
```

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                    case EVENT_DATE: criteriaQuery.orderBy(builder.asc(root.get("eventDate"))); break;
вот для этого перечисления можно было бы завести тег, и тогда `switch-case` почти никогда не понадобится

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            return repository.findAllById(ids);
можно использовать тернарный оператор

2023-09-17 08:09 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/enums/EventStates.java
> +    CANCELED("CANCELED");
Про это писал уже

2023-09-17 17:25 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/endpoints/admin/service/EventAdminService.java
> +            } else {
done

2023-09-17 17:25 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/endpoints/admin/service/EventAdminService.java
> +            return LocalDateTime.parse(input, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
done

2023-09-17 17:51 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/endpoints/admin/service/CompilatonAdminService.java
> +        compilationStorage.removeCompilation(compId);
done

2023-09-17 17:52 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/endpoints/admin/service/EventAdminService.java
> +            return LocalDateTime.parse(input, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
done

2023-09-17 17:52 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/endpoints/parents/EventService.java
> +                reqMap.put(request.getEvent().getId(), 1);
done p3 + p1

2023-09-17 17:53 UTC, Sintsoft commented on ewm-utility/pom.xml
> +        </dependency>
Прицепилось в одном из вариантов решения

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +            } else {
done

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        List<StatUriHitsResponseDTO> dtos;
done - removed

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +    public class Wrapper {
done - removed

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +        }
done - removed

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +    public class Wrapper {
done - removed

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/src/main/java/ru/practicum/client/StatisticClient.java
> +                "end", end.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
done - removed

2023-09-17 17:56 UTC, Sintsoft commented on ewm-statistic/statistic-client/pom.xml
> +        </dependency>
done - removed

2023-09-17 18:00 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/paticipation/enums/ParticipationRequestStatus.java
> +    private String code;
Без них работа с БД не ладится (

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            }
done

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            // TODO available
done

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/paticipation/dto/EventPartisipationDecisionDTO.java
> +    String status;
done

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                    case EVENT_DATE: criteriaQuery.orderBy(builder.asc(root.get("eventDate"))); break;
done

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            return repository.findAllById(ids);
done

2023-09-17 18:14 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/enums/EventStates.java
> +    CANCELED("CANCELED");
Для работы с БД

2023-09-18 08:11 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи с последним этапом диплома!

2023-09-18 09:29 UTC, merged