Feature rating events
Sintsoft/java-explore-with-me pull request #7
Opened 2023-09-21 20:41 UTC by Sintsoft

2023-09-24 17:47 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара мелких замечаний, которые надо исправить!

Желаю удачи!

2023-09-24 17:47 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +        try (Session session = sessionFactory.openSession();) {
Точка с запятой не нужна, `try with resources` и без этого работает

2023-09-24 17:47 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            }*/
удалить, если не нужно

2023-09-24 17:47 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                predicates.add(builder.isNotNull(root.get("publishedOn").as(LocalDateTime.class)));
А с текущим временем не надо сравнивать?
Просто `not null` достаточно?

2023-09-24 17:47 UTC, LexLippi commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                                "%" + searchString.toLowerCase() + "%"),
один раз можно этот темплейт собрать, чем три раза тратить время и память на создание новых строк

2023-09-25 04:58 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +        try (Session session = sessionFactory.openSession();) {
done

2023-09-25 04:58 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +            }*/
done

2023-09-25 05:08 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                predicates.add(builder.isNotNull(root.get("publishedOn").as(LocalDateTime.class)));
done

2023-09-25 05:08 UTC, Sintsoft commented on ewm-main/src/main/java/ru/practicum/model/event/repository/EventStorage.java
> +                                "%" + searchString.toLowerCase() + "%"),
fixed

2023-09-26 08:49 UTC, LexLippi commented
Привет!

Отличная работа!

Поздравляю тебя с окончанием курса Java-разработчик, надеюсь, мои ревью были полезны тебе и еще помогут тебе становиться лучше, как специалисту.

Желаю удачи!

2023-09-27 07:07 UTC, merged